"""Small OpenVINO IR inspector used to freeze generated tensor contracts."""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path
from typing import Any
from xml.etree import ElementTree as ET


def _port_shape(port: ET.Element) -> list[int]:
    return [int(dim.text) for dim in port.findall("dim")]


def _semantic_element(element: ET.Element) -> dict[str, Any]:
    """Return deterministic executable-graph XML content.

    Model Optimizer appends a top-level <meta_data> section containing
    conversion provenance/CLI details. Those values do not participate in
    inference and may differ across preparation hosts, so only that section is
    excluded. Layer/edge/blob structure and all of their attributes remain part
    of the fingerprint.
    """
    children = [
        _semantic_element(child)
        for child in list(element)
        if child.tag != "meta_data"
    ]
    text = (element.text or "").strip()
    return {
        "tag": element.tag,
        "attributes": dict(sorted(element.attrib.items())),
        "text": text or None,
        "children": children,
    }


def _json_sha256(document: Any) -> str:
    payload = json.dumps(
        document,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
    ).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def graph_sha256(root: ET.Element) -> str:
    """Hash executable XML while preserving serializer IDs and ordering."""
    return _json_sha256(_semantic_element(root))


def canonical_graph_document(root: ET.Element) -> dict[str, Any]:
    """Return an ID/order-insensitive but structure-sensitive IR document.

    Layer numeric IDs and XML serialization order are Model Optimizer
    implementation details. Model Optimizer can also assign nondeterministic
    numeric suffixes to autogenerated Const nodes named Cast_<number>_const;
    those suffixes are normalized and disambiguated by their consumer edge.
    Canonical identity otherwise preserves names, types, precisions, data
    attributes, blobs, ports, dimensions and connectivity.
    """
    layers_node = root.find("layers")
    edges_node = root.find("edges")
    if layers_node is None or edges_node is None:
        raise ValueError("IR must contain layers and edges")

    layers_by_id: dict[str, ET.Element] = {}
    original_names: dict[str, str] = {}
    for layer in layers_node.findall("layer"):
        layer_id = layer.attrib["id"]
        name = layer.attrib.get("name", "")
        if not name:
            raise ValueError(f"IR layer {layer_id} has no stable name")
        layers_by_id[layer_id] = layer
        original_names[layer_id] = name

    raw_edges = list(edges_node.findall("edge"))
    outgoing_targets: dict[str, list[tuple[str, str | None, str | None]]] = {
        layer_id: [] for layer_id in layers_by_id
    }
    for edge in raw_edges:
        source_id = edge.attrib["from-layer"]
        target_id = edge.attrib["to-layer"]
        if source_id not in layers_by_id or target_id not in layers_by_id:
            raise ValueError("IR edge references unknown layer id")
        outgoing_targets[source_id].append(
            (
                original_names[target_id],
                edge.attrib.get("from-port"),
                edge.attrib.get("to-port"),
            )
        )

    auto_cast = re.compile(r"^(.*)Cast_\d+_const$")
    id_to_name: dict[str, str] = {}
    names: set[str] = set()
    for layer_id, layer in layers_by_id.items():
        name = original_names[layer_id]
        stable_name = name
        match = auto_cast.match(name)
        if layer.attrib.get("type") == "Const" and match:
            consumers = sorted(outgoing_targets[layer_id])
            consumer_key = ",".join(
                f"{target}:{from_port or ''}->{to_port or ''}"
                for target, from_port, to_port in consumers
            )
            stable_name = f"{match.group(1)}Cast_<auto>_const"
            if consumer_key:
                stable_name = f"{stable_name}@{consumer_key}"
        if stable_name in names:
            raise ValueError(f"canonical IR layer name is not unique: {stable_name}")
        names.add(stable_name)
        id_to_name[layer_id] = stable_name

    canonical_layers = []
    for layer_id, layer in layers_by_id.items():
        item = _semantic_element(layer)
        item["attributes"] = dict(item["attributes"])
        item["attributes"].pop("id", None)
        item["attributes"]["name"] = id_to_name[layer_id]
        canonical_layers.append(item)

    canonical_edges = []
    for edge in raw_edges:
        source_id = edge.attrib["from-layer"]
        target_id = edge.attrib["to-layer"]
        canonical_edges.append({
            "from_layer": id_to_name[source_id],
            "from_port": edge.attrib.get("from-port"),
            "to_layer": id_to_name[target_id],
            "to_port": edge.attrib.get("to-port"),
        })

    extras = [
        _semantic_element(child)
        for child in list(root)
        if child.tag not in {"layers", "edges", "meta_data"}
    ]
    extras.sort(key=lambda item: json.dumps(item, sort_keys=True, separators=(",", ":")))

    return {
        "network": {
            "attributes": dict(sorted(root.attrib.items())),
        },
        "layers": sorted(
            canonical_layers,
            key=lambda item: (
                item["attributes"].get("name", ""),
                item["attributes"].get("type", ""),
            ),
        ),
        "edges": sorted(
            canonical_edges,
            key=lambda item: (
                item["from_layer"],
                item["from_port"] or "",
                item["to_layer"],
                item["to_port"] or "",
            ),
        ),
        "extras": extras,
    }


def canonical_graph_sha256(root: ET.Element) -> str:
    return _json_sha256(canonical_graph_document(root))


def canonical_graph_manifest(root: ET.Element) -> dict[str, Any]:
    """Return a compact diagnostic manifest for cross-host IR comparison."""
    document = canonical_graph_document(root)
    layers = []
    for layer in document["layers"]:
        attributes = layer["attributes"]
        sections = []
        for child in layer["children"]:
            sections.append({
                "tag": child["tag"],
                "sha256": _json_sha256(child),
            })
        layers.append({
            "name": attributes.get("name", ""),
            "type": attributes.get("type", ""),
            "sha256": _json_sha256(layer),
            "attributes_sha256": _json_sha256(attributes),
            "sections": sections,
        })

    return {
        "canonical_graph_sha256": _json_sha256(document),
        "network": document["network"],
        "layer_count": len(document["layers"]),
        "edge_count": len(document["edges"]),
        "layers": layers,
        "edges": document["edges"],
        "extras_sha256": _json_sha256(document["extras"]),
    }


def inspect_ir(xml_path: Path, bin_path: Path | None = None) -> dict[str, Any]:
    root = ET.parse(xml_path).getroot()
    layers_node = root.find("layers")
    edges_node = root.find("edges")
    if layers_node is None or edges_node is None:
        raise ValueError("IR must contain layers and edges")

    layers = {}
    for layer in layers_node.findall("layer"):
        layer_id = layer.attrib["id"]
        input_ports = []
        input_node = layer.find("input")
        if input_node is not None:
            for port in input_node.findall("port"):
                input_ports.append({
                    "id": int(port.attrib["id"]),
                    "precision": port.attrib.get("precision", layer.attrib.get("precision")),
                    "shape": _port_shape(port),
                })

        output_ports = []
        output_node = layer.find("output")
        if output_node is not None:
            for port in output_node.findall("port"):
                output_ports.append({
                    "id": int(port.attrib["id"]),
                    "precision": port.attrib.get("precision", layer.attrib.get("precision")),
                    "shape": _port_shape(port),
                })
        layers[layer_id] = {
            "id": int(layer_id),
            "name": layer.attrib.get("name", ""),
            "type": layer.attrib.get("type", ""),
            "precision": layer.attrib.get("precision"),
            "input_ports": input_ports,
            "output_ports": output_ports,
        }

    outgoing = {layer_id: 0 for layer_id in layers}
    incoming = {layer_id: 0 for layer_id in layers}
    incoming_edges: dict[str, list[ET.Element]] = {
        layer_id: [] for layer_id in layers
    }
    for edge in edges_node.findall("edge"):
        source = edge.attrib["from-layer"]
        target = edge.attrib["to-layer"]
        if source in outgoing:
            outgoing[source] += 1
        if target in incoming:
            incoming[target] += 1
            incoming_edges[target].append(edge)

    # Only explicit graph data-input layers are model inputs. Const layers
    # also have zero incoming edges in IR v7, but they are embedded weights /
    # reshape metadata and must never appear in the external tensor contract.
    inputs = [
        layer
        for layer in layers.values()
        if layer["type"] in {"Input", "Parameter"} and layer["output_ports"]
    ]

    # IR v7 commonly exposes a model output as a sink computation layer with
    # an output port. IR v10 commonly appends an explicit Result sink that has
    # only an input port. For Result sinks, report the actual producer selected
    # by the incoming edge. Model Optimizer may rename that producer (for
    # example ONNX "logits" may become "/Transpose"), so higher-level model
    # validators must treat this as serializer provenance, not a stable logical
    # output name.
    outputs: list[dict[str, Any]] = []
    result_layer_ids: set[str] = set()
    for layer_id, layer in layers.items():
        if layer["type"] != "Result":
            continue
        result_layer_ids.add(layer_id)
        edges = incoming_edges[layer_id]
        if len(edges) != 1:
            raise ValueError(
                f"IR Result layer {layer['name']!r} must have exactly one incoming edge"
            )
        edge = edges[0]
        source_id = edge.attrib["from-layer"]
        producer = layers.get(source_id)
        if producer is None:
            raise ValueError(
                f"IR Result layer {layer['name']!r} references unknown producer {source_id}"
            )
        from_port = int(edge.attrib["from-port"])
        selected = [
            port for port in producer["output_ports"]
            if port["id"] == from_port
        ]
        if len(selected) != 1:
            # Some serializers keep the complete shape only on Result's input
            # port. Preserve the producer identity but use that port contract.
            result_port = int(edge.attrib["to-port"])
            selected = [
                port for port in layer["input_ports"]
                if port["id"] == result_port
            ]
        if len(selected) != 1:
            raise ValueError(
                f"could not resolve output port for IR Result layer {layer['name']!r}"
            )
        precision = selected[0]["precision"] or producer["precision"]
        outputs.append({
            "name": producer["name"],
            "type": producer["type"],
            "precision": precision,
            "ports": selected,
            "result_name": layer["name"],
        })

    for layer_id, layer in layers.items():
        if layer_id in result_layer_ids:
            continue
        if outgoing[layer_id] == 0 and layer["output_ports"]:
            outputs.append({
                "name": layer["name"],
                "type": layer["type"],
                "precision": layer["precision"],
                "ports": layer["output_ports"],
            })

    def compact(layer: dict[str, Any]) -> dict[str, Any]:
        return {
            "name": layer["name"],
            "type": layer["type"],
            "precision": layer["precision"],
            "ports": layer["output_ports"],
        }

    result = {
        "schema": "speech-asr/openvino-ir-contract",
        "version": 1,
        "network_name": root.attrib.get("name", ""),
        "ir_version": root.attrib.get("version"),
        "xml_sha256": hashlib.sha256(xml_path.read_bytes()).hexdigest(),
        "graph_sha256": graph_sha256(root),
        "canonical_graph_sha256": canonical_graph_sha256(root),
        "inputs": [compact(layer) for layer in sorted(inputs, key=lambda item: item["id"])],
        "outputs": sorted(
            outputs,
            key=lambda item: (item["name"], item["ports"][0]["id"]),
        ),
    }
    if bin_path is not None:
        result["bin_sha256"] = hashlib.sha256(bin_path.read_bytes()).hexdigest()
    if not result["inputs"] or not result["outputs"]:
        raise ValueError("could not identify IR input/output tensors")
    return result
