#!/usr/bin/env bash
# Materialise OpenVINO 2020.3.2's retired VPU firmware downloads locally.
# The payloads are device firmware and are shared by armv7, arm64 and amd64 hosts.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=platform.sh
source "${ROOT}/scripts/platform.sh"
TARGET_REQUEST="$(platform_default_request)"
while [[ $# -gt 0 ]]; do
    case "$1" in
        --platform) TARGET_REQUEST="$2"; shift 2 ;;
        -h|--help) echo "usage: $0 [--platform armv7|arm64|amd64]"; exit 0 ;;
        *) echo "unknown option: $1" >&2; exit 2 ;;
    esac
done
platform_load "${TARGET_REQUEST}"

SRC="${ROOT}/vendor/openvino-2020.3.2"
FW_SRC="${ROOT}/vendor/firmware"
DEPS="${ROOT}/vendor/deps"
[[ -d "${SRC}" ]] || { echo "missing OpenVINO source tree: ${SRC}" >&2; exit 1; }
[[ -d "${FW_SRC}" ]] || { echo "missing ${FW_SRC} (run scripts/fetch-runtime.sh)" >&2; exit 1; }

if [[ -f "${FW_SRC}/SHA256SUMS" ]]; then
    (cd "${FW_SRC}" && sha256sum -c SHA256SUMS)
fi

VER="$(sed -n 's/^set(FIRMWARE_PACKAGE_VERSION  *\([0-9][0-9]*\)).*$/\1/p' "${SRC}/inference-engine/cmake/vpu_dependencies.cmake")"
DEVICES="$(sed -n 's/^set(VPU_SUPPORTED_FIRMWARES  *\(.*\)).*$/\1/p' "${SRC}/inference-engine/cmake/vpu_dependencies.cmake")"
[[ -n "${VER}" && -n "${DEVICES}" ]] || { echo "could not read VPU firmware metadata from source" >&2; exit 1; }

echo "   target (host code):       ${TARGET}"
echo "   firmware payload:         shared/device-side"
echo "   firmware package version: ${VER}"
echo "   supported firmwares:      ${DEVICES}"
mkdir -p "${DEPS}"
python3 - "$DEPS" "$FW_SRC" "$VER" $DEVICES <<'PY'
import pathlib, sys, zipfile
deps, fw_src, ver, devices = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4:]
for dev in devices:
    fw = pathlib.Path(fw_src) / f"{dev}.mvcmd"
    if not fw.is_file():
        raise SystemExit(f"missing firmware payload: {fw}")
    out = pathlib.Path(deps) / f"firmware_{dev}_{ver}.zip"
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        z.write(fw, arcname=f"mvnc/{dev}.mvcmd")
    print(f"wrote {out.name} (mvnc/{dev}.mvcmd, {fw.stat().st_size} B)")
PY
cat > "${DEPS}/README.generated.txt" <<EOF_NOTE
Generated by scripts/prepare-deps.sh.
These archives contain VPU firmware only and are intentionally shared by the
armv7, arm64 and amd64 host builds. IE_PATH_TO_DEPS expects this flat directory.
Firmware package version: ${VER}
EOF_NOTE
ls -l "${DEPS}"
